//
// Copyright (c) 2026 MacShade Authors. All Rights Reserved.
// PROPRIETARY AND CONFIDENTIAL.
// UNAUTHORIZED COPYING, REVERSE ENGINEERING, REBRANDING, OR DISTRIBUTION IS STRICTLY PROHIBITED.
//

#import "FXChain.h"

namespace {
BOOL ChainError(NSError **error, NSString *message) {
    if (error) *error = [NSError errorWithDomain:@"MacShade.Chain" code:1
        userInfo:@{NSLocalizedDescriptionKey:message}];
    return NO;
}
NSString *FileKey(NSString *name) {
    return [[name stringByReplacingOccurrencesOfString:@"\\" withString:@"/"] lastPathComponent];
}
NSDictionary *UniformSnapshot(MSFXEffect *effect) {
    NSMutableDictionary *values = [NSMutableDictionary dictionary];
    for (NSDictionary *uniform in effect.uniforms)
        if (![uniform[@"source"] length]) values[uniform[@"name"]] = uniform[@"values"];
    return [values copy];
}
}

NSArray<NSDictionary *> *MSFXChainSpecifications(NSArray<NSDictionary *> *entries) {
    NSMutableArray *specs = [NSMutableArray array];
    for (NSDictionary *entry in entries) {
        MSFXEffect *effect = entry[@"effect"];
        [specs addObject:@{@"url":entry[@"url"], @"technique":effect ? effect.activeTechnique : entry[@"technique"] ?: @"",
            @"enabled":entry[@"enabled"] ?: @YES, @"values":effect ? UniformSnapshot(effect) : entry[@"values"] ?: @{},
            @"definitions":entry[@"definitions"] ?: @{}, @"strictValues":effect ? @NO : entry[@"strictValues"] ?: @YES}];
    }
    return [specs copy];
}

NSArray<NSDictionary *> *MSCompileFXChain(NSArray<NSDictionary *> *specifications,
    id<MTLDevice> device, NSUInteger width, NSUInteger height, NSArray<NSURL *> *includeDirectories, NSError **error) {
    NSUInteger enabledCount = 0;
    for (NSDictionary *spec in specifications) if (!spec[@"enabled"] || [spec[@"enabled"] boolValue]) ++enabledCount;
    if (specifications.count > 512 || enabledCount > 64) {
        ChainError(error,@"This preset exceeds MacShade's current limit of 64 active techniques or 512 listed techniques."); return nil;
    }
    NSMutableArray *entries = [NSMutableArray array];
    for (NSDictionary *spec in specifications) {
        NSURL *url = spec[@"url"];
        // TechniqueSorting commonly includes many disabled shaders. Preserve their
        // parameters without compiling or allocating GPU resources until enabled.
        if (spec[@"enabled"] && ![spec[@"enabled"] boolValue]) {
            [entries addObject:[spec copy]]; continue;
        }
        NSError *failure = nil;
        MSFXEffect *effect = [[MSFXEffect alloc] initWithURL:url device:device width:width height:height
            definitions:spec[@"definitions"] ?: @{} includeDirectories:includeDirectories error:&failure];
        NSString *technique = spec[@"technique"];
        if (effect && technique.length && ![effect selectTechniqueNamed:technique error:&failure]) effect = nil;
        if (effect) {
            NSMutableDictionary *known = [NSMutableDictionary dictionary];
            for (NSDictionary *uniform in effect.uniforms) known[uniform[@"name"]] = uniform;
            NSDictionary *values = spec[@"values"] ?: @{};
            for (NSString *name in values) {
                NSDictionary *uniform = known[name];
                // ReShade stores per-uniform shortcut bindings as Key<Uniform>.
                // They are input settings, not shader numeric values.
                if (!uniform && [name hasPrefix:@"Key"] && [values[name] count] == 4) continue;
                // Source values are generated by the host, never restored from a preset.
                if ([uniform[@"source"] length]) continue;
                if (!uniform || [values[name] count] != [uniform[@"components"] unsignedIntegerValue]) {
                    if (![spec[@"strictValues"] boolValue]) continue;
                    ChainError(&failure,[NSString stringWithFormat:@"Preset parameter %@ is missing or has the wrong number of components.",name]);
                    effect = nil; break;
                }
                if (![effect setUniformNamed:name values:values[name] error:&failure]) { effect = nil; break; }
            }
        }
        if (!effect) {
            ChainError(error,[NSString stringWithFormat:@"%@%@\n%@",url.lastPathComponent,
                technique.length ? [@" · " stringByAppendingString:technique] : @"",
                failure.localizedDescription ?: @"Could not compile this effect."]);
            return nil;
        }
        [entries addObject:@{@"url":url, @"effect":effect, @"enabled":spec[@"enabled"] ?: @YES,
            @"definitions":spec[@"definitions"] ?: @{}}];
    }
    return [entries copy];
}

NSArray<NSDictionary *> *MSFXLibrary(NSArray<NSURL *> *directories) {
    NSMutableArray *files = [NSMutableArray array];
    NSMutableSet *seen = [NSMutableSet set];
    NSFileManager *fm = NSFileManager.defaultManager;
    for (NSURL *root in directories) {
        NSDirectoryEnumerator *iterator = [fm enumeratorAtURL:root includingPropertiesForKeys:
            @[NSURLIsRegularFileKey,NSURLIsSymbolicLinkKey] options:NSDirectoryEnumerationSkipsHiddenFiles |
            NSDirectoryEnumerationSkipsPackageDescendants errorHandler:^BOOL(NSURL *url, NSError *error) {
                (void)url; (void)error; return YES;
            }];
        NSUInteger visited = 0;
        for (NSURL *url in iterator) {
            if (++visited > 20000 || files.count >= 4096) break;
            NSNumber *link = nil, *regular = nil;
            [url getResourceValue:&link forKey:NSURLIsSymbolicLinkKey error:nil];
            if (link.boolValue) { [iterator skipDescendants]; continue; }
            if (![url.pathExtension.lowercaseString isEqual:@"fx"]) continue;
            [url getResourceValue:&regular forKey:NSURLIsRegularFileKey error:nil];
            if (!regular.boolValue) continue;
            NSString *path = url.URLByStandardizingPath.path;
            if ([seen containsObject:path]) continue;
            [seen addObject:path];
            [files addObject:@{@"url":url, @"name":url.lastPathComponent.stringByDeletingPathExtension,
                @"subtitle":url.URLByDeletingLastPathComponent.lastPathComponent ?: @"Effects"}];
        }
    }
    return [files copy];
}

NSArray<NSDictionary *> *MSFXPresetSpecifications(MSFXPreset *preset, NSURL *presetURL,
    NSArray<NSDictionary *> *library, NSMutableArray<NSString *> *warnings, NSError **error) {
    NSMutableArray *specs = [NSMutableArray array];
    for (NSDictionary *entry in preset.entries) {
        NSString *file = FileKey(entry[@"file"] ?: @"");
        NSString *technique = entry[@"technique"];
        BOOL enabled = [entry[@"enabled"] boolValue];
        // ReShade stores shader basenames. Only resolve in the selected library or
        // adjacent preset directory; do not use arbitrary paths from INI content.
        NSMutableArray<NSURL *> *matches = [NSMutableArray array];
        if (file.length) {
            NSURL *adjacent = [presetURL.URLByDeletingLastPathComponent URLByAppendingPathComponent:file];
            BOOL directory = NO;
            if ([NSFileManager.defaultManager fileExistsAtPath:adjacent.path isDirectory:&directory] && !directory)
                [matches addObject:adjacent];
            if (!matches.count) for (NSDictionary *item in library) {
                NSURL *url = item[@"url"];
                if ([url.lastPathComponent caseInsensitiveCompare:file] == NSOrderedSame) [matches addObject:url];
            }
        } else {
            // Legacy presets have no file qualification. Infer only from a unique
            // matching shader basename; ambiguous names require a modern preset.
            for (NSDictionary *item in library) {
                NSURL *url = item[@"url"];
                if ([url.lastPathComponent.stringByDeletingPathExtension caseInsensitiveCompare:technique] == NSOrderedSame)
                    [matches addObject:url];
            }
        }
        if (matches.count != 1) {
            NSString *message = matches.count ? [NSString stringWithFormat:@"%@ matches multiple shader files. Keep one matching shader in the selected folders.",file.length ? file : technique]
                : [NSString stringWithFormat:@"Missing shader for %@. Add its effects folder, then import the preset again.",file.length ? file : technique];
            if (!enabled) { [warnings addObject:[@"Skipped disabled technique: " stringByAppendingString:message]]; continue; }
            if (matches.count == 0) { [warnings addObject:[@"Skipped unavailable effect: " stringByAppendingString:message]]; continue; }
            ChainError(error,message); return nil;
        }
        NSURL *url = matches.firstObject;
        NSString *section = nil;
        for (NSString *key in preset.uniformValues)
            if ([FileKey(key) caseInsensitiveCompare:url.lastPathComponent] == NSOrderedSame) { section = key; break; }
        NSDictionary *values = section ? preset.uniformValues[section] : @{};
        NSMutableDictionary *definitions = [preset.definitions mutableCopy];
        for (NSString *key in preset.effectDefinitions)
            if ([FileKey(key) caseInsensitiveCompare:url.lastPathComponent] == NSOrderedSame)
                [definitions addEntriesFromDictionary:preset.effectDefinitions[key]];
        NSString *depthConvention = definitions[@"RESHADE_DEPTH_INPUT_IS_REVERSED"];
        if (depthConvention && ![depthConvention isEqual:@"0"]) {
            definitions[@"RESHADE_DEPTH_INPUT_IS_REVERSED"] = @"0";
            [warnings addObject:@"Depth convention adapted to MacShade's forward depth input. Use Reversed Depth Input for a host that supplies reversed depth."];
        }
        [specs addObject:@{@"url":url, @"technique":technique, @"enabled":@(enabled),
            @"values":values ?: @{}, @"definitions":definitions, @"strictValues":@NO}];
    }
    if (specs.count == 0) {
        NSUInteger enabledCount = 0;
        for (NSDictionary *e in preset.entries) if ([e[@"enabled"] boolValue]) ++enabledCount;
        if (enabledCount > 0) {
            NSString *lastWarn = warnings.lastObject ?: @"All enabled shaders in this preset are missing.";
            if ([lastWarn hasPrefix:@"Skipped unavailable effect: "]) {
                lastWarn = [lastWarn substringFromIndex:[@"Skipped unavailable effect: " length]];
            }
            ChainError(error, lastWarn);
            return nil;
        }
    }
    return [specs copy];
}

NSString *MSFXChainPresetString(NSArray<NSDictionary *> *entries, NSError **error) {
    NSMutableArray *references = [NSMutableArray array];
    NSMutableDictionary *values = [NSMutableDictionary dictionary], *definitions = [NSMutableDictionary dictionary];
    NSMutableDictionary<NSString *,NSString *> *paths = [NSMutableDictionary dictionary];
    NSMutableSet *compiledFiles = [NSMutableSet set];
    for (NSDictionary *entry in entries) {
        NSURL *url = entry[@"url"];
        NSString *file = url.lastPathComponent;
        NSString *key = file.lowercaseString;
        if (paths[key] && ![paths[key] isEqual:url.path]) {
            ChainError(error,@"Two selected shaders share a filename. ReShade presets need distinct shader filenames."); return nil;
        }
        paths[key] = url.path;
        MSFXEffect *effect = entry[@"effect"];
        NSDictionary *snapshot = effect ? UniformSnapshot(effect) : entry[@"values"] ?: @{};
        if (effect && [compiledFiles containsObject:file] && ![values[file] isEqual:snapshot]) {
            ChainError(error,@"Techniques from the same shader have different parameter values. ReShade presets share those values."); return nil;
        }
        if (effect || !values[file]) values[file] = snapshot;
        if (effect) [compiledFiles addObject:file];
        definitions[file] = entry[@"definitions"] ?: @{};
        [references addObject:@{@"file":file,@"technique":effect ? effect.activeTechnique : entry[@"technique"] ?: @"",@"enabled":entry[@"enabled"] ?: @YES}];
    }
    return [MSFXPreset stringWithEntries:references uniformValues:values definitions:@{} effectDefinitions:definitions error:error];
}
